global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'alerts@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'smtp-user'
        auth_identity: 'smtp-user'
        auth_password: 'smtp-password'

inhibit_rules: []
