// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/conversation/helpers/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:frontend/core/audio_recorder/audio_recorder_service.dart'
    as _i8;
import 'package:frontend/core/error/failures.dart' as _i10;
import 'package:frontend/features/auth/data/datasources/auth_local_datasource.dart'
    as _i7;
import 'package:frontend/features/conversation/domain/entities/conversation_entity.dart'
    as _i4;
import 'package:frontend/features/conversation/domain/repositories/conversation_repository.dart'
    as _i3;
import 'package:frontend/features/conversation/domain/usecases/connect_conversation_usecase.dart'
    as _i9;
import 'package:frontend/features/conversation/domain/usecases/end_session_usecase.dart'
    as _i14;
import 'package:frontend/features/conversation/domain/usecases/send_audio_chunk_usecase.dart'
    as _i12;
import 'package:frontend/features/conversation/domain/usecases/start_session_usecase.dart'
    as _i11;
import 'package:frontend/features/conversation/domain/usecases/switch_speaker_usecase.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i3.ConversationRepository {
  @override
  _i4.WebSocketConnectionStatus get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i4.WebSocketConnectionStatus.disconnected,
            returnValueForMissingStub:
                _i4.WebSocketConnectionStatus.disconnected,
          )
          as _i4.WebSocketConnectionStatus);

  @override
  _i5.Stream<_i4.ConversationEvent> connect(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [accessToken]),
            returnValue: _i5.Stream<_i4.ConversationEvent>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i4.ConversationEvent>.empty(),
          )
          as _i5.Stream<_i4.ConversationEvent>);

  @override
  void startSession({
    required String? sourceLanguage,
    required String? targetLanguage,
    _i4.ConversationSpeaker? speaker = _i4.ConversationSpeaker.speakerA,
  }) => super.noSuchMethod(
    Invocation.method(#startSession, [], {
      #sourceLanguage: sourceLanguage,
      #targetLanguage: targetLanguage,
      #speaker: speaker,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void sendAudioMetadata({
    required int? sampleRate,
    required String? audioFormat,
    required _i4.ConversationSpeaker? speaker,
    required String? sourceLanguage,
    required String? targetLanguage,
  }) => super.noSuchMethod(
    Invocation.method(#sendAudioMetadata, [], {
      #sampleRate: sampleRate,
      #audioFormat: audioFormat,
      #speaker: speaker,
      #sourceLanguage: sourceLanguage,
      #targetLanguage: targetLanguage,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void sendAudioChunk(_i6.Uint8List? chunk) => super.noSuchMethod(
    Invocation.method(#sendAudioChunk, [chunk]),
    returnValueForMissingStub: null,
  );

  @override
  void endUtterance() => super.noSuchMethod(
    Invocation.method(#endUtterance, []),
    returnValueForMissingStub: null,
  );

  @override
  void changeSpeaker(_i4.ConversationSpeaker? speaker) => super.noSuchMethod(
    Invocation.method(#changeSpeaker, [speaker]),
    returnValueForMissingStub: null,
  );

  @override
  void endSession() => super.noSuchMethod(
    Invocation.method(#endSession, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i7.AuthLocalDataSource {
  @override
  _i5.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveUserData({
    required String? userId,
    required String? email,
    String? name,
    String? role,
    String? status,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [], {
              #userId: userId,
              #email: email,
              #name: name,
              #role: role,
              #status: status,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String?>?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i5.Future<Map<String, String?>?>.value(),
            returnValueForMissingStub:
                _i5.Future<Map<String, String?>?>.value(),
          )
          as _i5.Future<Map<String, String?>?>);

  @override
  _i5.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasTokens, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [AudioRecorderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorderService extends _i1.Mock
    implements _i8.AudioRecorderService {
  @override
  bool get isRecording =>
      (super.noSuchMethod(
            Invocation.getter(#isRecording),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPaused =>
      (super.noSuchMethod(
            Invocation.getter(#isPaused),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<bool> hasPermission({bool? request = true}) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [], {#request: request}),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> startRecording() =>
      (super.noSuchMethod(
            Invocation.method(#startRecording, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i8.RecordingResult?> stopRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopRecording, []),
            returnValue: _i5.Future<_i8.RecordingResult?>.value(),
            returnValueForMissingStub: _i5.Future<_i8.RecordingResult?>.value(),
          )
          as _i5.Future<_i8.RecordingResult?>);

  @override
  _i5.Future<_i5.Stream<_i6.Uint8List>> startStreamRecording() =>
      (super.noSuchMethod(
            Invocation.method(#startStreamRecording, []),
            returnValue: _i5.Future<_i5.Stream<_i6.Uint8List>>.value(
              _i5.Stream<_i6.Uint8List>.empty(),
            ),
            returnValueForMissingStub:
                _i5.Future<_i5.Stream<_i6.Uint8List>>.value(
                  _i5.Stream<_i6.Uint8List>.empty(),
                ),
          )
          as _i5.Future<_i5.Stream<_i6.Uint8List>>);

  @override
  _i5.Future<void> stopStreamRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopStreamRecording, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelRecording() =>
      (super.noSuchMethod(
            Invocation.method(#cancelRecording, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pauseRecording() =>
      (super.noSuchMethod(
            Invocation.method(#pauseRecording, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resumeRecording() =>
      (super.noSuchMethod(
            Invocation.method(#resumeRecording, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ConnectConversationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectConversationUseCase extends _i1.Mock
    implements _i9.ConnectConversationUseCase {
  @override
  _i2.Either<_i10.Failure, _i5.Stream<_i4.ConversationEvent>> call(
    _i9.ConnectConversationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _FakeEither_0<_i10.Failure, _i5.Stream<_i4.ConversationEvent>>(
                  this,
                  Invocation.method(#call, [params]),
                ),
            returnValueForMissingStub:
                _FakeEither_0<_i10.Failure, _i5.Stream<_i4.ConversationEvent>>(
                  this,
                  Invocation.method(#call, [params]),
                ),
          )
          as _i2.Either<_i10.Failure, _i5.Stream<_i4.ConversationEvent>>);
}

/// A class which mocks [StartSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartSessionUseCase extends _i1.Mock
    implements _i11.StartSessionUseCase {
  @override
  void call(_i11.StartSessionParams? params) => super.noSuchMethod(
    Invocation.method(#call, [params]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SendAudioChunkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendAudioChunkUseCase extends _i1.Mock
    implements _i12.SendAudioChunkUseCase {
  @override
  bool call(_i6.Uint8List? chunk) =>
      (super.noSuchMethod(
            Invocation.method(#call, [chunk]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [SwitchSpeakerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwitchSpeakerUseCase extends _i1.Mock
    implements _i13.SwitchSpeakerUseCase {
  @override
  void call(_i4.ConversationSpeaker? newSpeaker) => super.noSuchMethod(
    Invocation.method(#call, [newSpeaker]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EndSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEndSessionUseCase extends _i1.Mock implements _i14.EndSessionUseCase {
  @override
  void call() => super.noSuchMethod(
    Invocation.method(#call, []),
    returnValueForMissingStub: null,
  );
}
