"""Add category to vocabulary

Revision ID: 58c7c580d366
Revises: 4fe145d789b0
Create Date: 2026-05-18 09:10:00.044517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c7c580d366'
down_revision: Union[str, None] = '4fe145d789b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabularies', 'category')
    # ### end Alembic commands ###
