"""Drop category str add category_id and table

Revision ID: edcbb197afc1
Revises: 58c7c580d366
Create Date: 2026-05-18 09:18:23.901546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcbb197afc1'
down_revision: Union[str, None] = '58c7c580d366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_categories_id'), 'vocabulary_categories', ['id'], unique=False)
    op.add_column('vocabularies', sa.Column('category_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'vocabularies', 'vocabulary_categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('vocabularies', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vocabularies', type_='foreignkey')
    op.drop_column('vocabularies', 'category_id')
    op.drop_index(op.f('ix_vocabulary_categories_id'), table_name='vocabulary_categories')
    op.drop_table('vocabulary_categories')
    # ### end Alembic commands ###
